room/urls.py
from django.urls import path
from . import views

# app_name = 'room'

urlpatterns = [
    path('', views.home, name='room-home'),
    path('about/', views.about, name='room-about'),
    path('book/<int:date_id>/', views.book, name='room-book'),
    path('book/booked/<int:room_id>', views.booked, name = 'room-booked'),
    path('bookings/', views.bookings, name = 'bookings'),
    path('bookings/<int:room_id>/delete', views.delete, name='booking-delete'),
    #path('bookings/<int:room_id>/', views.BookingsDetailView.as_view(), name='booking-detail'),
    #path('bookings/<int:room_id>/delete', views.BookingsDeleteView.as_view(), name='booking-delete'),
    # path('book/booked', views.booked, name='room-booked'),
]

slot_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('room/', include('room.urls'))         # sees what comes after room on the server and takes that from room.urls, can use room_dev as well instead of room
    path('', include('room.urls')),
    path('', include('customer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.timezone import now

# Database creation for slot booking
class Booking(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    date = models.DateField(default = timezone.now)
    time_start = models.TimeField(default = timezone.now)
    time_end = models.TimeField(default = timezone.now)
    room_number = models.CharField(max_length = 50)

    # to show on admin page
    def __str__(self):
        return self.customer
    
    def __str__(self):
        return str(self.date)

    def __str__(self):
        return self.time_start

    def __str__(self):
        return self.time_end

    def __str__(self):
        return self.room_number

class Room(models.Model):
    room_number = models.CharField(max_length = 100)
    
    def __str__(self):
        return self.room_number
    
class Slot(models.Model):
    room = models.ForeignKey(Room, on_delete = models.CASCADE)
    date = models.DateField(default = timezone.now)
    time_start = models.TimeField(default = timezone.now)
    time_end = models.TimeField(default = timezone.now)
    status = models.CharField(max_length = 50, default = "available")

    def __str__(self):
        return str(self.date)

    def __str__(self):
        return str(self.time_start)

    def __str__(self):
        return str(self.time_end)

    def __str__(self):
        return (self.status)

room/views.py
from django.shortcuts import render, get_object_or_404, redirect
#from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Room, Slot, Booking
from datetime import datetime, timedelta, date
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView, DetailView
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# get rooms

rooms = Room.objects.all().order_by('room_number')

def home(request):    
    request.session['on_date'] = datetime.now().strftime("%B %d, %Y")
    return render(request, 'room/home.html', {'date':date.today()})

def about(request):
    return render(request, 'room/about.html', {'title':'About'})

@login_required
def book(request, date_id):
    page = request.GET.get('page', 1)
    paginator = Paginator(rooms, 10)
    try:
        prooms = paginator.page(page)
    except PageNotAnInteger:
        prooms = paginator.page(1)
    except EmptyPage:
        prooms = paginator.page(paginator.num_pages)
    dates = []
    for i in range(14):
        dates.append(date.today() + timedelta(days=i))
    if request.method == 'POST':
        d = request.POST.get('date_id')
        on_date = datetime.strptime(d, "%B %d, %Y").date()
        request.session['on_date'] = d
        context = {
            'rooms' : prooms,
            'dates' : dates,
            'on_date' : on_date,
        }
    else:
        on_date = datetime.strptime(request.session['on_date'], "%B %d, %Y").date()
        context = {
            'rooms' : prooms,
            'dates' : dates,
            'on_date' : on_date,
        }
    
    return render(request, 'room/book.html', context)

@login_required
# show time slot booked
def booked(request, room_id):
    # model = Booking  
    if request.method == 'POST':
        slots = request.POST.get('room_id').split('|')
        number = slots[0].strip()
        request.session['number'] = number
        slot = slots[1]
        slot_list = slot.split('-')
        s = slot_list[0].strip()
        start = datetime.strptime(s, '%I:%M %p')
        e = slot_list[1].strip()
        end = datetime.strptime(e, '%I:%M %p')
        d = slots[2].strip()
        date = datetime.strptime(d, "%B %d, %Y").date()
        creator = request.user
        u = User.objects.get(username__iexact = str(creator))
        email = u.email
        msg = EmailMessage(
            subject='Booking confirmed!',
            body='Your booking:\nDate : ' + str(d) + '\nRoom No. : ' + number + '\nTime Slot : ' + str(s) + ' to ' + str(e),
            to=[email],
        )
        msg.send()
        b = Booking(customer = creator, date = date, time_start = start, time_end = end, room_number = number)
        b.save()
        room_booked = Slot.objects.filter(room = room_id, date = date, time_start = start, time_end = end, status = "available")
        room_booked.update(status = 'booked')
    context = {
        'number':number,
        'slot':slot,        
        'creator':creator,
    }
    messages.success(request, f'Booking confirmed! Booking details have been mailed to you.')
    return render(request, 'room/home.html', {'date':date.today()})

@login_required
def bookings(request):
    request.session['on_date'] = datetime.now().strftime("%B %d, %Y")
    creator = request.user
    bookings = Booking.objects.filter(customer = creator).order_by('-date')
    context = {
        'bookings':bookings,
        'date':date.today(),
    }
    return render(request, 'room/bookings.html', context)

@login_required
def delete(request, room_id):
    try:
        if request.method == 'POST':
            slots = request.POST.get('room_id').split('|')
            number = slots[0].strip()
            request.session['number'] = number
            slot = slots[1]
            slot_list = slot.split('-')
            s = slot_list[0].strip()
            start = datetime.strptime(s, '%I:%M %p')
            e = slot_list[1].strip()
            end = datetime.strptime(e, '%I:%M %p')
            d = slots[2].strip()
            date = datetime.strptime(d, "%B %d, %Y").date()
            creator = request.user
            u = User.objects.get(username__iexact = str(creator))
            email = u.email
            msg = EmailMessage(
                subject='Booking deleted☹!',
                body='Your booking for ' + number + ' on ' + str(d) + ' for the time slot ' + str(s) + ' to ' + str(e) + ' has been deleted.',
                to=[email],
            )
            msg.send()
            i = Room.objects.get(room_number = number)
            b = Booking.objects.get(customer = creator, date = date, time_start = start, time_end = end, room_number = number)
            b.delete()
            room_booked = Slot.objects.filter(room = i.id, date = date, time_start = start, time_end = end, status = "booked")
            room_booked.update(status = 'available')

    except:
        print('Booking does not exist!') 
    messages.success(request, f'Booking deleted!')
    return redirect(bookings)


'''class BookingsDetailView(DetailView):
    model = Booking
    pk_url_kwarg = 'room_id'            # template name = <app>/<model>_<viewtype>.html

class BookingsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Booking
    success_url = '/'
    pk_url_kwarg = 'room_id'
    
    def test_func(self):
        booking = self.get_object()
        if self.request.user == booking.customer:
            return True
        else:
            return False'''

room/templates/room/about.html
{% extends "room/base.html" %}
{% block content %}    
    <div class="col-md-12">
        <h1>ABOUT RACE FOR SPACE</h1>
    </div>
    <div class="col-md-9" style="float: left;">
        <article class="media content-section box-shadow" style="border-radius: 15px;">
            <div class="media-body">
                <div class="article-metadata">
                    <h2 class="article-title font-weight-light">
                        Hey Folks! Welcome to Race For Space, your ultimate room slot booking system on the go! Enjoy booking rooms with us!<br><br>
                    </h2>
                    <h3 class="article-title font-weight-light">
                        Thank You!
                    </h3>
                </div>
            </div>
        </article>
    </div>
    <div class="col-md-3" style="float: right;">
        <div class="alert alert-success" style="border-radius: 15px;">
                <p><b>Note : </b>You need to log in/sign up to start booking rooms</p>
                <p>Thank You!</p>
        </div>
    </div>
        
{% endblock content %}    

room/templates/room/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Faster One' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'room/main.css' %}">
    {% if title %}
        <title>Room Slot Booking - {{ title }}</title>
    {% else %}
        <title>Room Slot Booking</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" data-toggle="tooltip" data-placement="bottom" title="Home" style="font-family: Faster One; font-size: 28px;" href="{% url 'room-home' %}">Race For Space</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <a href="{% url 'bookings' %}">
                  <button class="btn btn-outline-light" style="border-width: 2px; font-weight: bold;" type="submit">
                    My Bookings
                  </button>
                </a>
                {% else %}
                  <a  class="nav-item nav-link" style="font-weight: bold;" href="{% url 'login' %}">
                    Login
                  </a>
                  <a href="{% url 'room-register' %}">
                    <button class="btn btn-outline-light" style="border-width: 2px; font-weight: bold;" type="submit">
                      Register
                    </button>
                  </a>
                {% endif %}
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                <a class="nav-item nav-link fa fa-home fa-2x" data-toggle="tooltip" data-placement="bottom" title="Home" aria-hidden="true" href="{% url 'room-home' %}"></a>
                <a class="nav-item nav-link fa fa-question fa-2x" data-toggle="tooltip" data-placement="bottom" title="About" aria-hidden="true" href="{% url 'room-about' %}"></a>
                
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" data-toggle="tooltip" data-placement="bottom" title="Profile" href="{% url 'profile' %}"><img class="rounded-circle article-img" src = "{{ user.profile.image.url }}"></a>
                  <a class="nav-item nav-link fa fa-sign-out fa-2x" data-toggle="tooltip" data-placement="bottom" title="Log Out" aria-hidden="true" href="{% url 'logout' %}?next={% url 'room-home' %}"></a>
                
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-12">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% if password %}
            <div class="alert alert-success">
              An email has been sent to your email id with instructions to reset your password!
            </div>
            {% endif %}
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>
      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

room/templates/room/book.html
{% extends "room/base.html" %}
{% block content %}   
<div class="col-md-12">
    <h2>BOOK A ROOM</h2>
</div>
<div class="col-md-3" style="float: right;">
    <article class="media content-section box-shadow" style="border-radius: 15px; ">
        <div class="media-body">
            <div class="article-metadata">
                <h2 class="article-title font-weight-light" style="border-bottom: 1px solid rgba(0, 0, 0, 0.20);">Dates</h2>
        <ul class="list-group text-center">
          {% for date in dates %}  
                <form method="POST" action="{% url 'room-book' date|date:'d' %}">
                    {% csrf_token %}             
                    {% if date == on_date %}
                        <button class="btn btn-primary" style="border: none; font-weight: bold;" type="submit" name = "date_id" id = "date_id" value = "{{ date|date:'F d, Y' }}">     
                    {% else %}
                        <button class="btn btn-outline-primary" style="border: none; font-weight: bold;" type="submit" name = "date_id" id = "date_id" value = "{{ date|date:'F d, Y' }}">
                    {% endif %}
                            <li style="background-color: transparent; border: none; list-style-type: none;"> {{ date|date:'F d, Y' }}   </li>
                        </button>           
                </form>       
          {% endfor %}
        </ul>
            </div>
        </div>
    </article>
</div>
    {% for room in rooms %}  
    <div class="col-md-9" style="float: left;">
    <article class="media content-section box-shadow" style="border-radius: 15px;">
        <div class="media-body">
        <div class="article-metadata">
            <h2 class="article-title font-weight-light" style="border-bottom: 1px solid rgba(0, 0, 0, 0.20);">{{ room.room_number }}</h2>           
            <!--<h2><a class="article-title" href="#">{{ post.title }}</a></h2>-->
            {% for slot in room.slot_set.all %}
                {% if slot.date == on_date %}
                    {% if slot.status == 'booked' %}
                        <button class="btn btn-secondary" style="border-width: 2px; font-weight: bold; margin: 3px;" disabled>{{ slot.time_start|time:'h:i A' }} - {{ slot.time_end|time:'h:i A' }}</button>
                    {% else %}
                    <div style="float: left;">
                    <form method="POST" action="{% url 'room-booked' room.id %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-primary" style="border-width: 2px; font-weight: bold; margin: 3px;" type="submit" name = "room_id" id = "room_id" value = "{{ room.room_number }} | {{ slot.time_start|date:'h:i A' }} - {{ slot.time_end|date:'h:i A' }} | {{ slot.date}}">
                            {{ slot.time_start|time:'h:i A' }} - {{ slot.time_end|time:'h:i A' }}
                        </button>
                    </form>
                    </div>
                    {% endif %}                    
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </article>
    </div>
    {% empty %}
        <div class="col-md-12">
            <h2 class="article-title font-weight-light">No rooms available!</h2>
        </div>
    {% endfor %}
    
    {% if rooms.paginator.page_range|length > 1 %}
    <div class="col-md-9">
      {% if rooms.has_previous %}
        <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-primary mb-4" href="?page={{ rooms.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in rooms.paginator.page_range %}
        {% if rooms.number == num %}
          <a class="btn btn-primary mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > rooms.number|add:'-3' and num < rooms.number|add:'3' %}
          <a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>     
        {% endif %}
      {% endfor %}

      {% if rooms.has_next %}
        <a class="btn btn-outline-primary mb-4" href="?page={{ rooms.next_page_number }}">Next</a>
        <a class="btn btn-outline-primary mb-4" href="?page={{ rooms.paginator.num_pages }}">Last</a>
      {% endif %}
    </div>
    {% endif %}
    
    <!--<ul class="pagination">
        {% if rooms.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ rooms.previous_page_number }}">&laquo</a></li>
        {% endif %}
        {% for i in rooms.paginator.page_range %}
        {% if rooms.number == i %}
            <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if rooms.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ rooms.next_page_number }}">&raquo</a></li>
        {% endif %}
    </ul>-->

{% endblock content %}    

room/templates/room/booked.html
{% extends "room/base.html" %}
{% block content %}   
    <article class="media content-section">
        <div class="media-body">
            <h2>{{ number }} has been booked for the time slot {{ slot }} by {{creator}}!</h2>
            <h2>You can go to "My Bookings" to view rooms booked by you.</h2>
            <a href="{% url 'room-book' %}">
                <button class="btn btn-outline-primary" style="border-width: 2px; font-weight: bold;" type="submit">
                    Continue booking
                </button>
            </a>
        </div>
    </article>
{% endblock content %}    

room/templates/room/bookings.html
{% extends "room/base.html" %}
{% block content %}   
<h2>BOOKINGS</h2>
    {% for booking in bookings %}

    <article class="media content-section box-shadow" style="border-radius: 15px;">
        
        <div class="media-body">
          <div class="article-metadata" style="border-bottom: 1px solid rgba(0, 0, 0, 0.20);">            
            <small class="text-muted">{{ booking.date }}</small>
          </div>
          <form method="POST" action="{% url 'booking-delete' booking.id %}">
            {% csrf_token %}
          <div style="float:right;">
            <button class="btn btn-outline-danger btn-sm mt-1 mb-1" style="border-width: 2px; font-weight: bold;" type="submit" name = "room_id" id = "room_id" value = "{{ booking.room_number }} | {{ booking.time_start|date:'h:i A' }} - {{ booking.time_end|date:'h:i A' }} | {{ booking.date }}">
              Delete
            </button>
        </div>
        </form>
          <h2 class="article-title font-weight-light" data-toggle="tooltip" data-placement="bottom">{{ booking.room_number }}</h2>
          
          <p class="article-content">{{ booking.time_start|date:'h:i A' }} to {{ booking.time_end|date:'h:i A' }}</p>
          <!--{% if object.customer == user %}
              <div>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'booking-delete' object.id%}">Delete</a>
              </div>
          {% endif %}-->
        </div>
    </article>
    {% empty %}
    <h2 class="article-title font-weight-light" data-toggle="tooltip" data-placement="bottom">No bookings!</h2>
    {% endfor %}
            
    
            <a href="{% url 'room-book' date|date:'d' %}">
                <button class="btn btn-outline-primary" style="border-width: 2px; font-weight: bold; margin-bottom: 15px;" type="submit">
                    Continue booking
                </button>
            </a>
            
        
{% endblock content %}    

room/templates/room/home.html
{% extends "room/base.html" %}
{% block content %}
    <article class="media content-section box-shadow" style="border-radius: 15px;">
        <div class="media-body">
            <div class="article-metadata">
            <h1>WELCOME TO ROOM SLOT BOOKING SYSTEM!</h1><br>
                <a href="{% url 'room-book' date|date:'d' %}">
                    <button class="btn btn-outline-primary" style="border-width: 2px; font-weight: bold;" type="submit">
                        Start Booking
                    </button>
                </a>
                <br>
            </div>
            <!--<h2><a class="article-title" href="#">{{ post.title }}</a></h2>-->
        </div>
    </article>
    
{% endblock content %}